export const paths = {
    start: '/',
    button: '/components/button',
    breadcrumbs: '/components/breadcrumbs',
    link: '/components/link',
    checkbox: '/components/checkbox',
    switch: '/components/switch',
    radio: '/components/radio',
    radioGroup: '/components/radiogroup',
    badge: '/components/badge',
    card: '/components/card',
    tooltip: '/components/tooltip',
    textField: '/components/textfield',
    menu: '/components/menu',
    fab: '/components/fab',
    iconButton: '/components/iconbutton',
    chip: '/components/chip',
    testButton: '/test/button',
    color: '/colors',
    collapse: '/components/collapse',
    accordion: '/components/accordion',
    tabs: '/components/tabs',
    toolbar: '/components/toolbar',
    dialog: '/components/dialog',
    box: '/components/box',
    spinner: '/components/spinner',
    animation: '/components/animation',
    list: '/components/list',
    listbox: '/components/listbox',
    select: '/components/select',
    progress: '/components/progress',
    slider: '/components/slider',
    drawer: '/components/drawer',
    bottomSheet: '/components/bottomsheet',
    fields: '/components/fields',
    fieldset: '/components/fieldset',
    calendar: '/components/calendar',
    toast: '/components/toast',
    avatar: '/components/avatar',
    rating: '/components/rating',
    status: '/components/status',
    dataTable: '/extra/datatable',
    catchAll: '*',
};

export const HOME_PATH = paths.start;
